#Numerical Python(Numpy) - Part 1

In [1]:
# de facto standard (사실상의 표준)
import numpy as np   #기본으로 이렇게 시작

In [2]:
a = [1, 2, 3]
a*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [3]:
list(map(lambda x : 3*x, a))

[3, 6, 9]

In [4]:
b = np.array([1,2,3,])
b * 3

array([3, 6, 9])

## 1. Numpy Dimensional array

In [5]:
a = np.array([1,4,5,8], float)
a

array([1., 4., 5., 8.])

In [6]:
type(a)

numpy.ndarray

In [7]:
a.dtype, a.shape

(dtype('float64'), (4,))

## Array shape

In [8]:
# Vector (1차원)
vector = np.array([1,4,5,8])
vector.shape

(4,)

In [22]:
# Matrix (2차원)
matrix = np.array([[1,2,3], [4,5,6]])
print(matrix.shape)
print(matrix)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [16]:
# Tensor (3차원)
tensor = np.arange(1,25).reshape(2,3,4)
print(tensor)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [17]:
# elemnets의 갯수
vector.size, matrix.size, tensor.size

(4, 6, 24)

In [18]:
# data type
#float32: 32bit로 표시 - single precision
#float64: 63bit로 표시 - double precision
a = np.array([1,2,3,], dtype=np.float32)
a

array([1., 2., 3.], dtype=float32)

In [20]:
b = np.array([1,2,3], dtype = np.int16)
b

array([1, 2, 3], dtype=int16)

### reshape

In [23]:
matrix.shape

(2, 3)

In [31]:
matrix.reshape(6,)

array([1, 2, 3, 4, 5, 6])

In [29]:
matrix.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [36]:
# -1은 numpy가 알아서 맞춰줌 (단, size가 동일)
matrix.reshape(-1,)

array([1, 2, 3, 4, 5, 6])

In [37]:
matrix.reshape(3, -1)  #차원이 달라도 가능 size가 동일

array([[1, 2],
       [3, 4],
       [5, 6]])

In [40]:
tensor.reshape(4, -1)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

### flatten

In [49]:
tensor.reshape(-1,)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [43]:
tensor.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

## 3. Indexing & Slicing

### Indexing

In [45]:
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
matrix[0][1]

2

In [48]:
matrix[0,1]    #Numpy에서는 가능

2

In [51]:
tensor[1,1,2]

19

### slicing

In [52]:
b = np.arange(16).reshape(4, -1)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [53]:
#5,6,9,10
b[1:3, 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [54]:
# 5,6,7,9,10,11
b[1:3, 1:]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [55]:
# 1,3,9,11      
b[::2, 1::2]        # 증가폭, 건너뛰기 명심

array([[ 1,  3],
       [ 9, 11]])

In [62]:
# X는 앞에 3열, y는 마지막열
X, y = b[:,:-1], b[:,-1]
X.shape, y.shape

((4, 3), (4,))